# Generated by Django 4.2.3 on 2023-07-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='prompt',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='refraim',
            field=models.TextField(max_length=1000),
        ),
    ]
