# Generated by Django 4.2.3 on 2023-07-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_conversation_prompt_alter_conversation_refraim'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_favorite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
