# Generated by Django 4.2.3 on 2023-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_conversation_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conclusion',
            field=models.TextField(default='No conclusion made, old model', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
