# Generated by Django 4.2.3 on 2023-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_conversation_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conclusion',
            field=models.TextField(default='None', max_length=1000),
        ),
    ]
